apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: grayround
  name: grayround
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grayround
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grayround
    spec:
      containers:
      - image: hellokyumin/grayround:v1.0
        name: grayround
        ports:
        - containerPort: 80
        resources: {}
status: {}
